# SPDX-FileCopyrightText: 2024 grow platform GmbH
#
# SPDX-License-Identifier: MIT

workItems:
  query: "SELECT [System.Id], [System.State] FROM WorkItems WHERE [System.TeamProject] = @project AND [System.WorkItemType] == 'Epic'"
  neededFields:
    - "TargetDate"
  evaluate:
    settings:
      dueDateFieldName: "TargetDate"
      closedStates:
        - "Closed"
        - "Done"
    checks:
      dataExists: true
      fields:
        priority:
          fieldName: "State"
          conditions:
            resolved:
              - "Closed"
              - "Done"
  children:
    get: true
    evaluate:
      checks:
        fields:
          state:
            fieldName: "State"
            conditions:
              resolved:
                - "Closed"
                - "Done"
