rules:
  - id: artifactory-identity-tokens
    category: general
    title: Artifactory Identity Token Rule
    severity: HIGH
    keywords:
      - eyJ
    regex: '["'']?(?P<secret>eyJ[A-Za-z0-9_=-]{2,}\.[A-Za-z0-9_=-]{2,}\.[A-Za-z0-9_.+\/=-]{2,})["'']?'
enable-builtin-rules:
  - github-pat
  - github-oauth
  - github-app-token
  - github-refresh-token
  - private-key
  - pypi-upload-token
  - bitbucket-client-id
  - bitbucket-client-secret
  - new-relic-user-api-key
  - new-relic-user-api-id
  - new-relic-browser-api-token
  - npm-access-token
  - pulumi-api-token
