apiVersion: v1
kind: Service
metadata:
  labels:
    app: mailhog
  name: mailhog
spec:
  type: NodePort
  ports:
    - name: smtp
      port: 1025
      nodePort: 30117
      protocol: TCP
      targetPort: 1025
    - name: web
      port: 8025
      nodePort: 30118
      protocol: TCP
      targetPort: 8025
  selector:
    app: mailhog
