# SPDX-FileCopyrightText: 2024 grow platform GmbH
#
# SPDX-License-Identifier: MIT

ci:
  skip: [madge, check-yaml, biome-check]
default_language_version:
  python: python3
repos:
  ####
  ## Licenses and copyright
  ####
  - repo: https://github.com/fsfe/reuse-tool
    rev: v5.0.2
    hooks:
      - id: reuse-lint-file
        files: '\.(adb|adoc|ads|aes|ahk|ahkl|aidl|applescript|arb|asax|asc|asciidoc|ashx|asm|asmx|aspx|aux|awk|axd|bash|bat|bats|bb|bbappend|bbclass|bib|bzl|c|cabal|cc|cjs|cl|clj|cljc|cljs|cls|cmake|code-workspace|coffee|cpp|cs|csl|cson|css|csproj|csv|cu|cuh|cxx|d|dart|di|doc|docx|dotx|dts|dtsi|el|erl|ex|exs|f|fsproj|f03|f08|f90|f95|fish|fnl|fodp|fods|fodt|for|ftn|fpp|fs|fsx|ftl|gemspec|go|gradle|graphql|graphqls|gqls|groovy|h|ha|hbs|hcl|hh|hjson|hpp|hrl|hs|html|hx|hxsl|ini|ino|ipynb|iuml|j2|java|jinja|jinja2|jl|jpg|jpeg|js|json|json5|jsonc|jsp|jsx|jy|ksh|kt|kts|l|latex|ld|less|license|lisp|lsp|lua|m|m4|man|markdown|md|mjs|mk|ml|mli|nim.cfg|nim|nimble|nimrod|nix|odb|odf|odg|odm|odp|ods|odt|org|otp|ots|ott|pdf|pem|php|php3|php4|php5|pl|plantuml|png|po|pod|pot|ppt|pptx|pri|pro|props|properties|proto|ps1|psm1|pu|puml|pxd|py|pyi|pyw|pyx|qbs|qml|qrc|qss|R|rake|rb|rbw|rbx|rkt|Rmd|rs|rss|rst|s|sass|sbt|sc|scad|scala|scm|scpt|scptd|scss|scsyndef|sh|sld|sln|sls|sml|soy|sps|sql|sty|svg|svelte|swift|t|tcl|tex|textile|tf|tfvars|thy|toc|toml|ts|tsx|ttl|typ|ui|v|vala|vbproj|vhdl|vim|vm|vsh|vtl|vue|webp|xls|xlsx|xml|xq|xql|xqm|xqy|xquery|xsd|xsh|xsl|yaml|yml|zig|zsh)$|Dockerfile|Makefile|CMakeLists\.txt|Gemfile|Jenkinsfile|Rakefile|requirements\.txt'
        exclude: 'user-documentation/source/resources/features/image-source-information\.md|user-documentation/source/onboarding\.md'

  ####
  ## User documentation
  ####
  - repo: local
    hooks:
      - name: Check filenames in user documentation
        language: system
        id: file-names-in-user-docs
        entry: make -C user-documentation fnlint
        pass_filenames: false
        files: '^user-documentation/'
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.42.0
    hooks:
      - id: markdownlint
        args: [--disable=MD013, --disable=MD029, --disable=MD033]
        files: '^user-documentation/.*\.md'
  ####
  ## Common hooks
  ####
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
        args: ['--maxkb=1100']
      - id: debug-statements
      - id: check-toml
      - id: check-yaml
        exclude: '^(chart|qg-api-service/qg-api-service/integration-tests/mocks|qg-api-service/qg-api-service/src/namespace|qg-api-service/localdev|onyx/pkg|onyx/cmd|onyx/examples|onyx/internal|user-documentation|yaku-apps-typescript|qg-api-service/api-commons-lib/src/testdata)/'
      - id: end-of-file-fixer
        exclude: '^(onyx/pkg|onyx/cmd|onyx/examples|onyx/internal|yaku-apps-typescript|qg-api-service/api-commons-lib/src/testdata)/'
      - id: trailing-whitespace
        exclude: '^(qg-api-service/qg-api-service/src/namespace|onyx/pkg|onyx/cmd|onyx/examples|onyx/internal|yaku-apps-typescript|qg-api-service/api-commons-lib/src/testdata)/'
  #  ####
  #  ## Commit lint
  #  ####
  #  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
  #    rev: v8.0.0
  #    hooks:
  #      - id: commitlint
  #        stages: [commit-msg]
  ####
  ## TS / JS related
  ####
  - repo: https://github.com/biomejs/pre-commit
    rev: 'v0.5.0'
    hooks:
      - id: biome-check
        additional_dependencies: ['@biomejs/biome@1.9.4']
        exclude: '^(.*/\.vscode/.*|.*/bad_JSON_data\.json|qg-api-service/qg-api-service/oss/.*)$'
  - repo: https://github.com/B-S-F/madge-pre-commit
    rev: v0.0.3
    hooks:
      - id: madge
        args: [qg-api-service/qg-api-service/src]
  ####
  ## Python related
  ####
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.7.4
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
  ####
  ## Go related
  ####
  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.1
    hooks:
      - id: go-fmt
      - id: go-mod-tidy
