default_language_version:
  python: python3
repos:
  ####
  ## Common hooks
  ####
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
      - id: pretty-format-json
        exclude: '^(onyx/pkg|onyx/cmd|onyx/examples|onyx/internal)/'
      - id: check-toml
      - id: check-yaml
        exclude: '^(qg-api-service/qg-api-service/src/namespace|onyx/pkg|onyx/cmd|onyx/examples|onyx/internal)/'
      - id: end-of-file-fixer
        exclude: '^(onyx/pkg|onyx/cmd|onyx/examples|onyx/internal)/'
      - id: trailing-whitespace
        exclude: '^(qg-api-service/qg-api-service/src/namespace|onyx/pkg|onyx/cmd|onyx/examples|onyx/internal)/'
#  ####
#  ## Commit lint
#  ####
#  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
#    rev: v8.0.0
#    hooks:
#      - id: commitlint
#        stages: [commit-msg]
  ####
  ## TS / JS related
  ####
  - repo: https://github.com/biomejs/pre-commit
    rev: "v0.5.0"
    hooks:
      - id: biome-check
        additional_dependencies: ["@biomejs/biome@1.9.4"]
        exclude: '^(onyx/pkg|onyx/cmd|onyx/examples|onyx/internal)/'
  - repo: https://github.com/B-S-F/madge-pre-commit
    rev: v0.0.2
    hooks:
      - id: madge
        args: [qg-api-service/qg-api-service/src]
  ####
  ## Python related
  ####
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.7.2
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
  ####
  ## Go related
  ####
  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.1
    hooks:
      - id: go-fmt
      - id: go-mod-tidy
