ci:
  skip: [madge, check-yaml, biome-check]
default_language_version:
  python: python3
repos:
  - repo: local
    hooks:
      - name: Check filenames in user documentation
        language: system
        id: file-names-in-user-docs
        entry: make -C user-documentation fnlint
        pass_filenames: false
        files: '^user-documentation/'
      - name: Lint Markdown files in user-documentation
        language: system
        id: markdown-lint
        entry: npx -y markdownlint-cli --disable MD013 MD029 MD033 --
        files: '^user-documentation/.*\.md'
  ####
  ## Common hooks
  ####
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
        args: ['--maxkb=1100']
      - id: debug-statements
      - id: check-toml
      - id: check-yaml
        exclude: '^(qg-api-service/qg-api-service/src/namespace|onyx/pkg|onyx/cmd|onyx/examples|onyx/internal|yaku-apps-typescript|qg-api-service/api-commons-lib/src/testdata)/'
      - id: end-of-file-fixer
        exclude: '^(onyx/pkg|onyx/cmd|onyx/examples|onyx/internal|yaku-apps-typescript|qg-api-service/api-commons-lib/src/testdata)/'
      - id: trailing-whitespace
        exclude: '^(qg-api-service/qg-api-service/src/namespace|onyx/pkg|onyx/cmd|onyx/examples|onyx/internal|yaku-apps-typescript|qg-api-service/api-commons-lib/src/testdata)/'
  #  ####
  #  ## Commit lint
  #  ####
  #  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
  #    rev: v8.0.0
  #    hooks:
  #      - id: commitlint
  #        stages: [commit-msg]
  ####
  ## TS / JS related
  ####
  - repo: https://github.com/biomejs/pre-commit
    rev: 'v0.5.0'
    hooks:
      - id: biome-check
        additional_dependencies: ['@biomejs/biome@1.9.4']
        exclude: '^(onyx/.vscode|onyx/pkg|onyx/cmd|onyx/examples|onyx/internal|yaku-apps-typescript|user-documentation|qg-api-service/api-commons-lib/src/testdata)/'
  - repo: https://github.com/B-S-F/madge-pre-commit
    rev: v0.0.3
    hooks:
      - id: madge
        args: [qg-api-service/qg-api-service/src]
  ####
  ## Python related
  ####
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.7.2
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
  ####
  ## Go related
  ####
  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.1
    hooks:
      - id: go-fmt
      - id: go-mod-tidy
