# SPDX-FileCopyrightText: 2024 grow platform GmbH
#
# SPDX-License-Identifier: MIT

ci:
  skip: [madge, check-yaml, biome-check]
default_language_version:
  python: python3
repos:
  ####
  ## Licenses and copyright
  ####
  - repo: https://github.com/fsfe/reuse-tool
    rev: v5.0.2
    hooks:
      - id: reuse-lint-file
        files: '\.(applescript|aspx|bat|bib|c|cpp|f|ftl|hbs|hs|html|jinja|jinja2|jl|lisp|lsp|m4|md|ml|f90|puml|plantuml|py|rst|tex|ts|man|vim|yaml|xq|xquery)$'
        exclude: 'user-documentation/source/resources/features/image-source-information\.md|user-documentation/source/onboarding\.md'

  ####
  ## User documentation
  ####
  - repo: local
    hooks:
      - name: Check filenames in user documentation
        language: system
        id: file-names-in-user-docs
        entry: make -C user-documentation fnlint
        pass_filenames: false
        files: '^user-documentation/'
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.42.0
    hooks:
      - id: markdownlint
        args: [ --disable=MD013, --disable=MD029, --disable=MD033 ]
        files: '^user-documentation/.*\.md'
  ####
  ## Common hooks
  ####
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
        args: ['--maxkb=1100']
      - id: debug-statements
      - id: check-toml
      - id: check-yaml
        exclude: '^(qg-api-service/qg-api-service/src/namespace|onyx/pkg|onyx/cmd|onyx/examples|onyx/internal|yaku-apps-typescript|qg-api-service/api-commons-lib/src/testdata)/'
      - id: end-of-file-fixer
        exclude: '^(onyx/pkg|onyx/cmd|onyx/examples|onyx/internal|yaku-apps-typescript|qg-api-service/api-commons-lib/src/testdata)/'
      - id: trailing-whitespace
        exclude: '^(qg-api-service/qg-api-service/src/namespace|onyx/pkg|onyx/cmd|onyx/examples|onyx/internal|yaku-apps-typescript|qg-api-service/api-commons-lib/src/testdata)/'
  #  ####
  #  ## Commit lint
  #  ####
  #  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
  #    rev: v8.0.0
  #    hooks:
  #      - id: commitlint
  #        stages: [commit-msg]
  ####
  ## TS / JS related
  ####
  - repo: https://github.com/biomejs/pre-commit
    rev: 'v0.5.0'
    hooks:
      - id: biome-check
        additional_dependencies: ['@biomejs/biome@1.9.4']
        exclude: '^(onyx/.vscode|onyx/pkg|onyx/cmd|onyx/examples|onyx/internal|yaku-apps-typescript|user-documentation|qg-api-service/api-commons-lib/src/testdata)/'
  - repo: https://github.com/B-S-F/madge-pre-commit
    rev: v0.0.3
    hooks:
      - id: madge
        args: [qg-api-service/qg-api-service/src]
  ####
  ## Python related
  ####
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.7.4
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
  ####
  ## Go related
  ####
  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.1
    hooks:
      - id: go-fmt
      - id: go-mod-tidy
