# SPDX-FileCopyrightText: 2024 grow platform GmbH
#
# SPDX-License-Identifier: MIT

metadata:
  version: v1
header:
  name: MACMA
  version: 1.16.0
autopilots:
  git-autopilot:
    run: |
      git-fetcher
      json-evaluator
    env:
      GIT_FETCHER_API_TOKEN: ${{ secrets.GIT_FETCHER_API_TOKEN }}
      GIT_FETCHER_CONFIG_FILE_PATH: git-fetcher-config.yml
      GIT_FETCHER_OUTPUT_FILE_PATH: git-fetcher-data.json
      GIT_FETCHER_SERVER_API_URL: ${{ vars.GIT_FETCHER_SERVER_API_URL }}
      GIT_FETCHER_SERVER_AUTH_METHOD: token
      GIT_FETCHER_SERVER_TYPE: github
      JSON_CONFIG_FILE: json-evaluator-config.yaml
      JSON_INPUT_FILE: git-fetcher-data.json
finalize:
  run: |
    html-finalizer
chapters:
  "1":
    title: Project management
    requirements:
      "1.15":
        title: Make sure all release required changes are done
        text: Make sure all release required changes are done
        checks:
          "1":
            title: Check the status of release version Pull requests
            automation:
              autopilot: git-autopilot
