# SPDX-FileCopyrightText: 2024 grow platform GmbH
#
# SPDX-License-Identifier: MIT

name: Doing Merge check

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-run-tests:
    permissions:
      pull-requests: write
      contents: read
    uses: ./.github/workflows/build-and-run-test-base.yml
    secrets: inherit
