# SPDX-FileCopyrightText: 2024 grow platform GmbH
#
# SPDX-License-Identifier: MIT

name: Doing PR check

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-run-tests:
    permissions:
      pull-requests: write
      contents: read
    uses: ./.github/workflows/build-and-run-test-base.yml
    secrets: inherit
