python_tests(
    dependencies=[
        "3rdparty:reqs#pytest-mock",
        "3rdparty:reqs#requests-mock",
    ],
    skip_bandit=True,
    skip_mypy=True,
)


python_test_utils(
    name="test_utils",
    skip_mypy=True,
)
