# SPDX-FileCopyrightText: 2024 grow platform GmbH
#
# SPDX-License-Identifier: MIT

# This is an example config for:
# RAM/ROM Splunk fetcher
# RAM/ROM Splunk evaluator
header:
  name: MACMA
  version: 1.16.0
globals:
  azureBase: https://dev.azure.com/myorg/myproject/myfolder
  avscannerBase: https://example.com/mysubscription
components:
  webApp:
    version: 1.16.5
autopilots:
  splunk-autopilot:
    run: |
      splunk-fetcher
      echo {\"sources\": [\"README.md\"]}
      splunk-evaluator
    env:
      SPLUNK_USERNAME: ${env.SPLUNK_USERNAME} # TODO: change this to your username (or add it as secret)
      SPLUNK_PASSWORD: ${env.SPLUNK_PASSWORD} # TODO: change this to your password (or add it as secret)
      splunk_result_file: splunk_result.json
      check: ${check.id}
reports:
  splunk: splunk-autopilot
finalize:
  run: |
    export ASSESSMENT_TYPE_ID=3c233adc-89b1-43fe-a761-0039104eca0b
    export ASSESSMENT_LEVEL_ID=a7e0802c-4060-4a31-ba58-c48bc7ea06a8
    export PROJECT_ID=30b7c81b-726a-4cde-9589-7c05ddc9dbfd # TODO: change this to your project id (if it does not exist generate it with the OneQ cli)
    export CATALOG_ID=f19202f1-b4f9-4ac5-beca-36ef939d68f5 # TODO: change this to your catalog id (generate this for your qg-config with the OneQ cli)
    export BASIC_AUTH_TOKEN=${env.BASIC_AUTH_TOKEN} # TODO: change this to your oneq auth token (or add it as secret)
    oneq finalize
    html-finalizer
    zip-finalizer
dependencies:
  # Remove this as soon as qg-cli with oneq finalizer is released to prod
  oneq-finalizer: git+https://${GITHUB_PRIVATE_ACCESSTOKEN}@github.exmple.com/

allocations:
  '1':
    title: Project management
    requirements:
      '1.15':
        title: ROM/RAM usage is within defined budget
        text: >-
          ROM/RAM usage is within defined budget
        checks:
          '1':
            title: Retrieve and check ROM/RAM usage from Splunk
            reports:
              - splunk
