# SPDX-FileCopyrightText: 2024 grow platform GmbH
#
# SPDX-License-Identifier: MIT

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: aqua
resources:
  - pvc.yaml
  - postgres.yaml
  - service-postgres.yaml
  - init-db-config-map.yaml
