kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: yaku-postgres-pvc
  namespace: aqua
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
  storageClassName: standard
