apiVersion: v1
kind: Service
metadata:
  labels:
    app: yaku-postgres
  name: yaku-postgres
spec:
  type: NodePort
  ports:
    - port: 5432
      nodePort: 30114
      protocol: TCP
      targetPort: 5432
  selector:
    app: yaku-postgres
