{{- if or (not .Values.env.encryption_secret_name) (not .Values.env.encryption_secret_key) }}
apiVersion: v1
kind: Secret
metadata:
  name: yaku-default-key
  labels:
    {{- include "yaku.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Release.IsInstall }}
  default_key: {{ randAlphaNum 32 | b64enc | quote }}
  {{ else }}
  default_key:  {{ index (lookup "v1" "Secret" .Release.Namespace "yaku-default-key").data "default_key" }}
  {{ end }}
{{- end }}