{{- if and (not (eq (toString .Values.global.serviceAccount.create) "false")) .Values.global.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "yaku.serviceAccountName" . }}
  labels:
  {{- include "yaku.labels" . | nindent 4 }}
  {{- with .Values.global.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
