{{- if and (eq (toString .Values.global.minio.createCredentialsSecret) "true") .Values.global.minio.createCredentialsSecret }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Values.global.minio.credentialsSecretName }}
  labels:
  {{- include "yaku.labels" . | nindent 4 }}
data:
  rootUser: bWluaW9hZG1pbg==
  rootPassword: bWluaW9hZG1pbg==
{{- end }}