{{- if and (eq (toString .Values.postgres.enabled) "true") .Values.postgres.enabled (eq (toString .Values.postgres.createCredentialsSecret) "true") .Values.postgres.createCredentialsSecret }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Values.postgres.credentialsSecretName }}
data:
  postgresuser: cG9zdGdyZXM=
  postgrespassword: cG9zdGdyZXM=
{{- end }}
