metadata:
  version: v1
header:
  name: Integration Test
  version: 0.0.1
autopilots:
  findings-interface-1:
    run: |
      echo '{"result": {"criterion": "No findings", "fulfilled": true, "justification": "I am the reason 1"}}'
      echo '{"result": {"criterion": "No findings", "fulfilled": true, "justification": "I am the reason 2", "metadata":{"keyA":"valueA", "keyB":"valueB", "keyC":"valueC"}}}'
      echo '{"result": {"criterion": "No findings", "fulfilled": true, "justification": "I am the reason 3"}}'
      echo '{"result": {"criterion": "No findings", "fulfilled": false, "justification": "I am the reason 4", "metadata":{"keyA":"valueA", "keyB":"valueB", "keyC":"valueC"}}}'
      echo '{"result": {"criterion": "No findings", "fulfilled": false, "justification": "I am the reason 5"}}'
      echo '{"status": "RED", "reason": "Found 2 findings"}'
  findings-interface-2:
    run: |
      echo '{"result": {"criterion": "No findings", "fulfilled": false, "justification": "I am the reason 1"}}'
      echo '{"result": {"criterion": "No findings", "fulfilled": false, "justification": "I am the reason 2", "metadata":{"keyA":"valueA", "keyB":"valueB", "keyC":"valueC"}}}'
      echo '{"result": {"criterion": "No findings", "fulfilled": true, "justification": "I am the reason 3"}}'
      echo '{"result": {"criterion": "No findings", "fulfilled": true, "justification": "I am the reason 4", "metadata":{"keyA":"valueA", "keyB":"valueB", "keyC":"valueC"}}}'
      echo '{"result": {"criterion": "No findings", "fulfilled": true, "justification": "I am the reason 5"}}'
      echo '{"status": "RED", "reason": "Found 2 findings"}'
chapters:
  '1':
    title: Test config should work
    requirements:
      '1':
        title: Run free of findings
        checks:
          '1':
            title: Check for findings
            automation:
              autopilot: findings-interface-1
          '2':
            title: Check for findings
            automation:
              autopilot: findings-interface-2
