apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - pvs.yaml
  - service-creds.yaml
  - ./argo-workflows
  - ./postgres
  - ./keycloak
  - ./pgadmin
  - ./mailhog
