query: "project = AQUATEST and issuetype in ('Task')"
neededFields:
  - 'summary'
  - 'status'
  - 'issuetype'
  - 'assignee'
evaluate:
  fields:
    assignee:
      fieldName: 'assignee'
      conditions:
        expected:
          - 'XXX7XX'
    status:
      fieldName: 'status'
      conditions:
        expected:
          - 'Done'
