apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: yaku-pgadmin
  name: yaku-pgadmin
  namespace: aqua
spec:
  selector:
    matchLabels:
      app: yaku-pgadmin
  template:
    metadata:
      labels:
        app: yaku-pgadmin
      name: yaku-pgadmin
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: yaku-pgadmin
        image: dpage/pgadmin4:8.4
        env:
        - name: PGADMIN_LISTEN_ADDRESS
          value: "0.0.0.0"
        - name: PGADMIN_LISTEN_PORT
          value: "5050"
        - name: PGADMIN_DISABLE_POSTFIX
          value: "true"
        - name: PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION
          value: "False"
        - name: PGADMIN_DEFAULT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: service-creds
              key: pgadminpassword
        - name: PGADMIN_DEFAULT_EMAIL
          valueFrom:
            secretKeyRef:
              name: service-creds
              key: pgadminemail
        ports:
        - name: http
          containerPort: 5050
          protocol: TCP
        resources:
            requests:
              memory: "500Mi"
              cpu: "200m"
            limits:
              memory: "1Gi"
              cpu: "400m"
      nodeSelector:
        kubernetes.io/os: linux