apiVersion: v1
kind: Service
metadata:
  labels:
    app: yaku-pgdmin
  name: yaku-pgdmin
spec:
  type: NodePort
  ports:
    - port: 5050
      nodePort: 30116
      protocol: TCP
      targetPort: 5050
  selector:
    app: yaku-pgadmin