# Note (2024-04-26, wulmer):
#
# I had to disable this rule as it introduces a package requirement to
# a pants wheel from https://wheels.pantsbuild.org/simple, but so far
# there only seem to be versions of pants for Python 3.9 on this server
# So the lockfile generation failed if this rule was activated, because
# we currently have Python `interpreter_constraints` set to Python 3.10.

# pants_requirements(name="pants")

