# SPDX-FileCopyrightText: 2024 grow platform GmbH
#
# SPDX-License-Identifier: MIT

{{- if and (not (eq (toString .Values.enabled) "false")) .Values.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name:  yaku-probe-config
  labels:
  {{- include "yaku.labels" . | nindent 4 }}
data:
  probe.sh: |
    #!/bin/sh
    curl -X POST -d "{\"model\":\"llama3\"}" http://yaku-labs:11434/api/chat
{{- end }}
