# SPDX-FileCopyrightText: 2024 grow platform GmbH
#
# SPDX-License-Identifier: MIT

[tool.coverage.run]
omit = ["*/tests/**", "*/tests-pex/**", "*/tests-integration/**"]
branch = true

[tool.coverage.report]
omit = ["*/tests/**", "*/tests-pex/**", "*/tests-integration/**"]
skip_empty = false
skip_covered = false
show_missing = true
