[tool.isort]
profile = "black"
line_length = 95

[tool.black]
line-length = 95

[tool.ruff]
line-length = 95

[tool.ruff.lint]
select = ["D", "E", "F", "G", "I", "W"]
ignore = [
  "D100",
  "D101",
  "D102",
  "D103",
  "D104",
  "D105",
  "D107",
  "D203",
  "D212",
  "D406",
  "D407",
  "D413",
  "E203",
  "E501",
  "E712",
  "E711",
  "E722",
  "G004",
  "I001",
]
[tool.ruff.lint.extend-per-file-ignores]
"**/tests/*" = [
  "D100",
  "D101",
  "D102",
  "D103",
  "D104",
  "D205",
  "D400",
  "D415",
  "G004",
]
"**/tests-pex/*" = [
  "D100",
  "D101",
  "D102",
  "D103",
  "D104",
  "D205",
  "D400",
  "D415",
]
"**/tests-integration/*" = ["D100", "D101", "D102", "D103", "D104"]
"apps/excel-tools/src/yaku/excel_tools/utils/vendored/*" = ["D"]

[tool.coverage.run]
omit = ["*/tests/**", "*/tests-pex/**", "*/tests-integration/**"]
branch = true

[tool.coverage.report]
omit = ["*/tests/**", "*/tests-pex/**", "*/tests-integration/**"]
skip_empty = false
skip_covered = false
show_missing = true
