# SPDX-FileCopyrightText: 2024 grow platform GmbH
#
# SPDX-License-Identifier: MIT

workItems:
  query: "SELECT [System.Id], [System.State] FROM WorkItems WHERE [System.TeamProject] = @project AND [System.WorkItemType] == 'Task'"
  neededFields:
    - "AssignedTo"
    - "BugType"
    - "Microsoft.VSTS.Scheduling.TargetDate"
  evaluate:
    settings:
      dueDateFieldName: "DueDate"
    checks:
      fields:
        state:
          fieldName: "State"
          conditions:
            resolved:
              - "Closed"
        assignees:
          fieldName: "AssignedTo"
          conditions:
            expected:
              - "Name"
        bugType:
          fieldName: "BugType"
          conditions:
            illegal:
              - "Critical"
