// SPDX-FileCopyrightText: 2024 grow platform GmbH
//
// SPDX-License-Identifier: MIT

/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BuildingSilhouetteNatureCloudLG: typeof import(
      './src/icons/emptyStateIcons/BuildingSilhouetteNatureCloudLG.vue',
    )['default']
    BuildingSilhouetteNatureCloudSM: typeof import(
      './src/icons/emptyStateIcons/BuildingSilhouetteNatureCloudSM.vue',
    )['default']
    BuildingSilhouetteNatureCloudXS: typeof import(
      './src/icons/emptyStateIcons/BuildingSilhouetteNatureCloudXS.vue',
    )['default']
    DoorLockClosed: typeof import('./src/icons/DoorLockClosed.vue')['default']
    EmptyRelease: typeof import(
      './src/icons/releasePlanningIcons/EmptyRelease.vue',
    )['default']
    EmptyState: typeof import('./src/icons/EmptyState.vue')['default']
    EmptyState2: typeof import('./src/icons/EmptyState2.vue')['default']
    ErrorIndication: typeof import('./src/icons/ErrorIndication.vue')['default']
    ManuallyResolved: typeof import(
      './src/icons/findingsIcons/ManuallyResolved.vue',
    )['default']
    ManualMode: typeof import('./src/icons/ManualMode.vue')['default']
    ManualStatus_Failed: typeof import(
      './src/icons/manualStatusIcons/ManualStatus_Failed.vue',
    )['default']
    ManualStatus_NA: typeof import(
      './src/icons/manualStatusIcons/ManualStatus_NA.vue',
    )['default']
    ManualStatus_NotPassed: typeof import(
      './src/icons/manualStatusIcons/ManualStatus_NotPassed.vue',
    )['default']
    ManualStatus_Success: typeof import(
      './src/icons/manualStatusIcons/ManualStatus_Success.vue',
    )['default']
    ManualStatus_Unanswered: typeof import(
      './src/icons/manualStatusIcons/ManualStatus_Unanswered.vue',
    )['default']
    ManualStatus_Warning: typeof import(
      './src/icons/manualStatusIcons/ManualStatus_Warning.vue',
    )['default']
    PendingIcon: typeof import(
      './src/icons/runIcons/PendingIcon.vue',
    )['default']
    ResolvedCheck: typeof import(
      './src/icons/releasePlanningIcons/ResolvedCheck.vue',
    )['default']
    RobotBodyFilled: typeof import('./src/icons/RobotBodyFilled.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RunCompletedIcon: typeof import(
      './src/icons/runIcons/RunCompletedIcon.vue',
    )['default']
    RunFailedFilledIcon: typeof import(
      './src/icons/runIcons/RunFailedFilledIcon.vue',
    )['default']
    RunPendingIcon: typeof import(
      './src/icons/runIcons/RunPendingIcon.vue',
    )['default']
    RunRunningIcon: typeof import(
      './src/icons/runIcons/RunRunningIcon.vue',
    )['default']
    Success: typeof import('./src/icons/Success.vue')['default']
    TaskControlBtn: typeof import(
      './src/icons/releasePlanningIcons/TaskControlBtn.vue',
    )['default']
    UnFulFilledCheck: typeof import(
      './src/icons/runResultIcons/UnFulFilledCheck.vue',
    )['default']
    VuetifyAppIcon: typeof import(
      './src/components/atoms/VuetifyAppIcon.vue',
    )['default']
    VuetifyAppItem: typeof import(
      './src/components/molecules/VuetifyAppItem.vue',
    )['default']
    VuetifyApprover: typeof import(
      './src/components/molecules/VuetifyApprover.vue',
    )['default']
    VuetifyApproverListItem: typeof import(
      './src/components/molecules/VuetifyApproverListItem.vue',
    )['default']
    VuetifyApproverStatus: typeof import(
      './src/components/molecules/VuetifyApproverStatus.vue',
    )['default']
    VuetifyAppsDialog: typeof import(
      './src/components/organisms/VuetifyAppsDialog.vue',
    )['default']
    VuetifyAutopilotActions: typeof import(
      './src/components/molecules/VuetifyAutopilotActions.vue',
    )['default']
    VuetifyAutopilotLogsPanel: typeof import(
      './src/components/organisms/VuetifyAutopilotLogsPanel.vue',
    )['default']
    VuetifyAutopilotsView: typeof import(
      './src/components/organisms/VuetifyAutopilotsView.vue',
    )['default']
    VuetifyAvatar: typeof import(
      './src/components/molecules/VuetifyAvatar.vue',
    )['default']
    VuetifyBackLink: typeof import(
      './src/components/molecules/VuetifyBackLink.vue',
    )['default']
    VuetifyBannerContent: typeof import(
      './src/components/atoms/VuetifyBannerContent.vue',
    )['default']
    VuetifyBarChart: typeof import(
      './src/components/molecules/VuetifyBarChart.vue',
    )['default']
    VuetifyBlurBackground: typeof import(
      './src/components/atoms/VuetifyBlurBackground.vue',
    )['default']
    VuetifyBottomDialogPanel: typeof import(
      './src/components/organisms/VuetifyBottomDialogPanel.vue',
    )['default']
    VuetifyCloseEditConfigDialog: typeof import(
      './src/components/organisms/VuetifyCloseEditConfigDialog.vue',
    )['default']
    VuetifyCloseExcelToConfigDialog: typeof import(
      './src/components/organisms/VuetifyCloseExcelToConfigDialog.vue',
    )['default']
    VuetifyCodeCard: typeof import(
      './src/components/molecules/VuetifyCodeCard.vue',
    )['default']
    VuetifyCodeEditor: typeof import(
      './src/components/organisms/VuetifyCodeEditor.vue',
    )['default']
    VuetifyCodeEditorLayout: typeof import(
      './src/components/layouts/VuetifyCodeEditorLayout.vue',
    )['default']
    VuetifyCodeSnippetDescription: typeof import(
      './src/components/molecules/VuetifyCodeSnippetDescription.vue',
    )['default']
    VuetifyComment: typeof import(
      './src/components/molecules/VuetifyComment.vue',
    )['default']
    VuetifyCommentInput: typeof import(
      './src/components/atoms/VuetifyCommentInput.vue',
    )['default']
    VuetifyCommentsThread: typeof import(
      './src/components/organisms/VuetifyCommentsThread.vue',
    )['default']
    VuetifyCommentSuggestionsBox: typeof import(
      './src/components/molecules/VuetifyCommentSuggestionsBox.vue',
    )['default']
    VuetifyConfigInfo: typeof import(
      './src/components/molecules/VuetifyConfigInfo.vue',
    )['default']
    VuetifyConfigOverviewItem: typeof import(
      './src/components/organisms/VuetifyConfigOverviewItem.vue',
    )['default']
    VuetifyConfigsOverview: typeof import(
      './src/components/views/VuetifyConfigsOverview.vue',
    )['default']
    VuetifyConfigurationView: typeof import(
      './src/components/organisms/VuetifyConfigurationView.vue',
    )['default']
    VuetifyConfirmDialog: typeof import(
      './src/components/organisms/VuetifyConfirmDialog.vue',
    )['default']
    VuetifyContentNavigation: typeof import(
      './src/components/organisms/VuetifyContentNavigation.vue',
    )['default']
    VuetifyCopyConfigDialog: typeof import(
      './src/components/molecules/VuetifyCopyConfigDialog.vue',
    )['default']
    VuetifyCreateConfigDialog: typeof import(
      './src/components/organisms/VuetifyCreateConfigDialog.vue',
    )['default']
    VuetifyCrossNavigation: typeof import(
      './src/components/molecules/VuetifyCrossNavigation.vue',
    )['default']
    VuetifyDashboard: typeof import(
      './src/components/views/VuetifyDashboard.vue',
    )['default']
    VuetifyDashboardTile: typeof import(
      './src/components/layouts/VuetifyDashboardTile.vue',
    )['default']
    VuetifyDataProtectionPolicy: typeof import(
      './src/components/views/VuetifyDataProtectionPolicy.vue',
    )['default']
    VuetifyDeleteConfigurationConfirmation: typeof import(
      './src/components/organisms/VuetifyDeleteConfigurationConfirmation.vue',
    )['default']
    VuetifyDeleteFileDialogConfirmation: typeof import(
      './src/components/organisms/VuetifyDeleteFileDialogConfirmation.vue',
    )['default']
    VuetifyDeleteFindingCommentConfirmation: typeof import(
      './src/components/organisms/VuetifyDeleteFindingCommentConfirmation.vue',
    )['default']
    VuetifyDeleteReleaseDialog: typeof import(
      './src/components/organisms/VuetifyDeleteReleaseDialog.vue',
    )['default']
    VuetifyDeleteRunConfirmation: typeof import(
      './src/components/organisms/VuetifyDeleteRunConfirmation.vue',
    )['default']
    VuetifyDeleteSecretConfirmation: typeof import(
      './src/components/organisms/VuetifyDeleteSecretConfirmation.vue',
    )['default']
    VuetifyDeltaPill: typeof import(
      './src/components/atoms/VuetifyDeltaPill.vue',
    )['default']
    VuetifyDescription: typeof import(
      './src/components/molecules/VuetifyDescription.vue',
    )['default']
    VuetifyDevBanner: typeof import(
      './src/components/molecules/VuetifyDevBanner.vue',
    )['default']
    VuetifyDialogCloseRelease: typeof import(
      './src/components/organisms/ReleaseApproval/VuetifyDialogCloseRelease.vue',
    )['default']
    VuetifyDialogCreateRelease: typeof import(
      './src/components/organisms/ReleaseApproval/VuetifyDialogCreateRelease.vue',
    )['default']
    VuetifyDialogCreateTask: typeof import(
      './src/components/organisms/ReleaseApproval/VuetifyDialogCreateTask.vue',
    )['default']
    VuetifyDialogOverrideResultStatus: typeof import(
      './src/components/organisms/ReleaseApproval/VuetifyDialogOverrideResultStatus.vue',
    )['default']
    VuetifyDialogReleaseApproval: typeof import(
      './src/components/organisms/ReleaseApproval/VuetifyDialogReleaseApproval.vue',
    )['default']
    VuetifyDialogReleaseUpdateApprovalStatus: typeof import(
      './src/components/organisms/ReleaseApproval/VuetifyDialogReleaseUpdateApprovalStatus.vue',
    )['default']
    VuetifyDonutChart: typeof import(
      './src/components/atoms/VuetifyDonutChart.vue',
    )['default']
    VuetifyDoorLockClosed: typeof import(
      './src/icons/VuetifyDoorLockClosed.vue',
    )['default']
    VuetifyDownloadReleaseReport: typeof import(
      './src/components/views/VuetifyDownloadReleaseReport.vue',
    )['default']
    VuetifyEditConfig: typeof import(
      './src/components/views/VuetifyEditConfig.vue',
    )['default']
    VuetifyEditConfigMetadata: typeof import(
      './src/components/organisms/VuetifyEditConfigMetadata.vue',
    )['default']
    VuetifyEditGlobalVariables: typeof import(
      './src/components/molecules/VuetifyEditGlobalVariables.vue',
    )['default']
    VuetifyEditorCodePanel: typeof import(
      './src/components/organisms/VuetifyEditorCodePanel.vue',
    )['default']
    VuetifyEditorEditPanel: typeof import(
      './src/components/organisms/VuetifyEditorEditPanel.vue',
    )['default']
    VuetifyEditorHeader: typeof import(
      './src/components/organisms/VuetifyEditorHeader.vue',
    )['default']
    VuetifyEditReleaseMetadata: typeof import(
      './src/components/organisms/VuetifyEditReleaseMetadata.vue',
    )['default']
    VuetifyEditSecretDialog: typeof import(
      './src/components/organisms/VuetifyEditSecretDialog.vue',
    )['default']
    VuetifyEmptyRelease: typeof import(
      './src/icons/releasePlanningIcons/VuetifyEmptyRelease.vue',
    )['default']
    VuetifyEmptyState: typeof import(
      './src/icons/VuetifyEmptyState.vue',
    )['default']
    VuetifyEmptyState2: typeof import(
      './src/icons/VuetifyEmptyState2.vue',
    )['default']
    VuetifyEmptyTileContent: typeof import(
      './src/components/molecules/VuetifyEmptyTileContent.vue',
    )['default']
    VuetifyEnvironmentSwitch: typeof import(
      './src/components/organisms/VuetifyEnvironmentSwitch.vue',
    )['default']
    VuetifyErrorPage: typeof import(
      './src/components/views/VuetifyErrorPage.vue',
    )['default']
    VuetifyExcelToConfig: typeof import(
      './src/components/views/VuetifyExcelToConfig.vue',
    )['default']
    VuetifyExpandTextToggle: typeof import(
      './src/components/atoms/VuetifyExpandTextToggle.vue',
    )['default']
    VuetifyFileItem: typeof import(
      './src/components/molecules/VuetifyFileItem.vue',
    )['default']
    VuetifyFindingDetail: typeof import(
      './src/components/organisms/VuetifyFindingDetail.vue',
    )['default']
    VuetifyFindingItem: typeof import(
      './src/components/molecules/VuetifyFindingItem.vue',
    )['default']
    VuetifyFindingsOverview: typeof import(
      './src/components/views/VuetifyFindingsOverview.vue',
    )['default']
    VuetifyFindingsResults: typeof import(
      './src/components/views/VuetifyFindingsResults.vue',
    )['default']
    VuetifyHeader: typeof import(
      './src/components/organisms/VuetifyHeader.vue',
    )['default']
    VuetifyHoverableText: typeof import(
      './src/components/molecules/VuetifyHoverableText.vue',
    )['default']
    VuetifyInlineOrContext: typeof import(
      './src/components/layouts/VuetifyInlineOrContext.vue',
    )['default']
    VuetifyLastOpenedTile: typeof import(
      './src/components/organisms/VuetifyLastOpenedTile.vue',
    )['default']
    VuetifyLogs: typeof import(
      './src/components/molecules/VuetifyLogs.vue',
    )['default']
    VuetifyLogsPanel: typeof import(
      './src/components/organisms/VuetifyLogsPanel.vue',
    )['default']
    VuetifyMain: typeof import('./src/components/VuetifyMain.vue')['default']
    VuetifyManuallyResolved: typeof import(
      './src/icons/findingsIcons/VuetifyManuallyResolved.vue',
    )['default']
    VuetifyManualMode: typeof import(
      './src/icons/VuetifyManualMode.vue',
    )['default']
    VuetifyManualStatusForm: typeof import(
      './src/components/molecules/VuetifyManualStatusForm.vue',
    )['default']
    VuetifyMapping: typeof import(
      './src/components/organisms/configExcelGenerator/VuetifyMapping.vue',
    )['default']
    VuetifyMappingHelperDialog: typeof import(
      './src/components/molecules/VuetifyMappingHelperDialog.vue',
    )['default']
    VuetifyMappingTable: typeof import(
      './src/components/molecules/VuetifyMappingTable.vue',
    )['default']
    VuetifyMappingTableSelection: typeof import(
      './src/components/molecules/VuetifyMappingTableSelection.vue',
    )['default']
    VuetifyMarkdown: typeof import(
      './src/components/atoms/VuetifyMarkdown.vue',
    )['default']
    VuetifyMonacoEditor: typeof import(
      './src/components/organisms/VuetifyMonacoEditor.vue',
    )['default']
    VuetifyMostDecreasedQualityTile: typeof import(
      './src/components/organisms/VuetifyMostDecreasedQualityTile.vue',
    )['default']
    VuetifyMostFindingsTile: typeof import(
      './src/components/organisms/VuetifyMostFindingsTile.vue',
    )['default']
    VuetifyMostIncreasedQualityTile: typeof import(
      './src/components/organisms/VuetifyMostIncreasedQualityTile.vue',
    )['default']
    VuetifyNamespaceSwitch: typeof import(
      './src/components/molecules/VuetifyNamespaceSwitch.vue',
    )['default']
    VuetifyNoItems: typeof import(
      './src/components/organisms/VuetifyNoItems.vue',
    )['default']
    VuetifyOnboardingOverlay: typeof import(
      './src/components/organisms/VuetifyOnboardingOverlay.vue',
    )['default']
    VuetifyOssComplianceInformation: typeof import(
      './src/components/views/VuetifyOssComplianceInformation.vue',
    )['default']
    VuetifyOssComplianceItem: typeof import(
      './src/components/organisms/VuetifyOssComplianceItem.vue',
    )['default']
    VuetifyOverrideResultStatus: typeof import(
      './src/components/molecules/VuetifyOverrideResultStatus.vue',
    )['default']
    VuetifyOverviewItemLayout: typeof import(
      './src/components/layouts/VuetifyOverviewItemLayout.vue',
    )['default']
    VuetifyOverviewLayout: typeof import(
      './src/components/layouts/VuetifyOverviewLayout.vue',
    )['default']
    VuetifyOverviewList: typeof import(
      './src/components/layouts/VuetifyOverviewList.vue',
    )['default']
    VuetifyPendingIcon: typeof import(
      './src/icons/runIcons/VuetifyPendingIcon.vue',
    )['default']
    VuetifyPerformanceChart: typeof import(
      './src/components/molecules/VuetifyPerformanceChart.vue',
    )['default']
    VuetifyPerformanceTile: typeof import(
      './src/components/organisms/VuetifyPerformanceTile.vue',
    )['default']
    VuetifyPopoverInfo: typeof import(
      './src/components/molecules/VuetifyPopoverInfo.vue',
    )['default']
    VuetifyProcessingActionIndicator: typeof import(
      './src/components/molecules/VuetifyProcessingActionIndicator.vue',
    )['default']
    VuetifyQuickStartupDialog: typeof import(
      './src/components/organisms/VuetifyQuickStartupDialog.vue',
    )['default']
    VuetifyRelationGrid: typeof import(
      './src/components/molecules/VuetifyRelationGrid.vue',
    )['default']
    VuetifyReleaseChecksNavigator: typeof import(
      './src/components/organisms/VuetifyReleaseChecksNavigator.vue',
    )['default']
    VuetifyReleaseDetails: typeof import(
      './src/components/views/VuetifyReleaseDetails.vue',
    )['default']
    VuetifyReleaseDetailsChecksPager: typeof import(
      './src/components/organisms/VuetifyReleaseDetailsChecksPager.vue',
    )['default']
    VuetifyReleaseHistory: typeof import(
      './src/components/organisms/VuetifyReleaseHistory.vue',
    )['default']
    VuetifyReleaseHistoryItem: typeof import(
      './src/components/molecules/VuetifyReleaseHistoryItem.vue',
    )['default']
    VuetifyReleaseOverview: typeof import(
      './src/components/views/VuetifyReleaseOverview.vue',
    )['default']
    VuetifyReleaseOverviewItem: typeof import(
      './src/components/organisms/VuetifyReleaseOverviewItem.vue',
    )['default']
    VuetifyReleaseReportCheckFinding: typeof import(
      './src/components/molecules/VuetifyReleaseReportCheckFinding.vue',
    )['default']
    VuetifyReleaseReportCheckOverride: typeof import(
      './src/components/molecules/VuetifyReleaseReportCheckOverride.vue',
    )['default']
    VuetifyReleaseReportChecksSummary: typeof import(
      './src/components/organisms/VuetifyReleaseReportChecksSummary.vue',
    )['default']
    VuetifyReleaseReportMeta: typeof import(
      './src/components/molecules/VuetifyReleaseReportMeta.vue',
    )['default']
    VuetifyReleaseTask: typeof import(
      './src/components/organisms/VuetifyReleaseTask.vue',
    )['default']
    VuetifyReleaseTasksTab: typeof import(
      './src/components/organisms/VuetifyReleaseTasksTab.vue',
    )['default']
    VuetifyResizableThreeColumnLayout: typeof import(
      './src/components/layouts/VuetifyResizableThreeColumnLayout.vue',
    )['default']
    VuetifyResolvedCheck: typeof import(
      './src/icons/releasePlanningIcons/VuetifyResolvedCheck.vue',
    )['default']
    VuetifyResultError: typeof import(
      './src/components/organisms/configExcelGenerator/VuetifyResultError.vue',
    )['default']
    VuetifyResultItem: typeof import(
      './src/components/organisms/VuetifyResultItem.vue',
    )['default']
    VuetifyResultMetadata: typeof import(
      './src/components/organisms/VuetifyResultMetadata.vue',
    )['default']
    VuetifyRobotBodyFilled: typeof import(
      './src/icons/VuetifyRobotBodyFilled.vue',
    )['default']
    VuetifyRowSelection: typeof import(
      './src/components/organisms/configExcelGenerator/VuetifyRowSelection.vue',
    )['default']
    VuetifyRunCompletedIcon: typeof import(
      './src/icons/runIcons/VuetifyRunCompletedIcon.vue',
    )['default']
    VuetifyRunFailedOutlineIcon: typeof import(
      './src/icons/runIcons/VuetifyRunFailedOutlineIcon.vue',
    )['default']
    VuetifyRunOverviewItem: typeof import(
      './src/components/organisms/VuetifyRunOverviewItem.vue',
    )['default']
    VuetifyRunReportHeader: typeof import(
      './src/components/organisms/VuetifyRunReportHeader.vue',
    )['default']
    VuetifyRunReportNav: typeof import(
      './src/components/molecules/VuetifyRunReportNav.vue',
    )['default']
    VuetifyRunReportNavChapter: typeof import(
      './src/components/molecules/VuetifyRunReportNavChapter.vue',
    )['default']
    VuetifyRunReportNavCheck: typeof import(
      './src/components/molecules/VuetifyRunReportNavCheck.vue',
    )['default']
    VuetifyRunReportNavRequirement: typeof import(
      './src/components/molecules/VuetifyRunReportNavRequirement.vue',
    )['default']
    VuetifyRunReportResults: typeof import(
      './src/components/organisms/VuetifyRunReportResults.vue',
    )['default']
    VuetifyRunResultDescription: typeof import(
      './src/components/molecules/VuetifyRunResultDescription.vue',
    )['default']
    VuetifyRunResultOverview: typeof import(
      './src/components/atoms/VuetifyRunResultOverview.vue',
    )['default']
    VuetifyRunResults: typeof import(
      './src/components/views/VuetifyRunResults.vue',
    )['default']
    VuetifyRunRunningIcon: typeof import(
      './src/icons/runIcons/VuetifyRunRunningIcon.vue',
    )['default']
    VuetifyRunsOverview: typeof import(
      './src/components/views/VuetifyRunsOverview.vue',
    )['default']
    VuetifyRunStatus: typeof import(
      './src/components/molecules/VuetifyRunStatus.vue',
    )['default']
    VuetifyRuntimeClock: typeof import(
      './src/components/molecules/VuetifyRuntimeClock.vue',
    )['default']
    VuetifyScreenCenter: typeof import(
      './src/components/layouts/VuetifyScreenCenter.vue',
    )['default']
    VuetifySecrets: typeof import(
      './src/components/views/VuetifySecrets.vue',
    )['default']
    VuetifySelectableChartFilter: typeof import(
      './src/components/atoms/VuetifySelectableChartFilter.vue',
    )['default']
    VuetifySelectEnvironment: typeof import(
      './src/components/views/VuetifySelectEnvironment.vue',
    )['default']
    VuetifySelectFile: typeof import(
      './src/components/organisms/configExcelGenerator/VuetifySelectFile.vue',
    )['default']
    VuetifySettings: typeof import(
      './src/components/views/VuetifySettings.vue',
    )['default']
    VuetifyShowMore: typeof import(
      './src/components/atoms/VuetifyShowMore.vue',
    )['default']
    VuetifySidebarFlyout: typeof import(
      './src/components/atoms/VuetifySidebarFlyout.vue',
    )['default']
    VuetifySidePanel: typeof import(
      './src/components/layouts/VuetifySidePanel.vue',
    )['default']
    VuetifyStack: typeof import(
      './src/components/layouts/VuetifyStack.vue',
    )['default']
    VuetifyStatusPill: typeof import(
      './src/components/molecules/VuetifyStatusPill.vue',
    )['default']
    VuetifyStepHeading: typeof import(
      './src/components/organisms/configExcelGenerator/VuetifyStepHeading.vue',
    )['default']
    VuetifySummaryOfChecks: typeof import(
      './src/components/organisms/VuetifySummaryOfChecks.vue',
    )['default']
    VuetifyTableHandle: typeof import(
      './src/components/atoms/VuetifyTableHandle.vue',
    )['default']
    VuetifyTaskAssigneeDisplay: typeof import(
      './src/components/molecules/VuetifyTaskAssigneeDisplay.vue',
    )['default']
    VuetifyTaskControl: typeof import(
      './src/components/molecules/VuetifyTaskControl.vue',
    )['default']
    VuetifyTestRunPanel: typeof import(
      './src/components/organisms/VuetifyTestRunPanel.vue',
    )['default']
    VuetifyToolbar: typeof import(
      './src/components/molecules/VuetifyToolbar.vue',
    )['default']
    VuetifyTruncableText: typeof import(
      './src/components/atoms/VuetifyTruncableText.vue',
    )['default']
    VuetifyUserMenu: typeof import(
      './src/components/molecules/VuetifyUserMenu.vue',
    )['default']
    VuetifyViewLoadingIndicator: typeof import(
      './src/components/molecules/VuetifyViewLoadingIndicator.vue',
    )['default']
    VuetifyVisualAutopilotDialog: typeof import(
      './src/components/organisms/VuetifyVisualAutopilotDialog.vue',
    )['default']
    VuetifyVisualEditor: typeof import(
      './src/components/organisms/VuetifyVisualEditor.vue',
    )['default']
    VuetifyVisualNoSearchResults: typeof import(
      './src/components/molecules/VuetifyVisualNoSearchResults.vue',
    )['default']
    VuetifyWindowMaximized: typeof import(
      './src/icons/VuetifyWindowMaximized.vue',
    )['default']
    VuetifyWindowMinimized: typeof import(
      './src/icons/VuetifyWindowMinimized.vue',
    )['default']
    VuetifyWindowSmall: typeof import(
      './src/icons/VuetifyWindowSmall.vue',
    )['default']
    VuetifyWorldMap: typeof import('./src/icons/VuetifyWorldMap.vue')['default']
    VuetifyYakuDropdown: typeof import(
      './src/components/molecules/VuetifyYakuDropdown.vue',
    )['default']
    VuetifyYakuSelectOption: typeof import(
      './src/components/molecules/VuetifyYakuSelectOption.vue',
    )['default']
    WindowMaximized: typeof import('./src/icons/WindowMaximized.vue')['default']
    WindowMinimized: typeof import('./src/icons/WindowMinimized.vue')['default']
    WindowSmall: typeof import('./src/icons/WindowSmall.vue')['default']
    WorldMap: typeof import('./src/icons/WorldMap.vue')['default']
    YakuDropdown: typeof import(
      './src/components/molecules/YakuDropdown.vue',
    )['default']
    YakuSelectOption: typeof import(
      './src/components/molecules/YakuSelectOption.vue',
    )['default']
  }
}
