# SPDX-FileCopyrightText: 2024 grow platform GmbH
#
# SPDX-License-Identifier: MIT

$patch: delete
apiVersion: v1
kind: Secret
metadata:
  name: argo-postgres-config
---
$patch: delete
apiVersion: v1
kind: Secret
metadata:
  name: my-minio-cred
