apiVersion: v1
kind: Service
metadata:
  labels:
    app: yaku-keycloak
  name: yaku-keycloak
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 30115
      protocol: TCP
      targetPort: 8080
  selector:
    app: yaku-keycloak
