# SPDX-FileCopyrightText: 2024 grow platform GmbH
#
# SPDX-License-Identifier: MIT

workItems:
  query: "SELECT [System.Id], [System.State] FROM WorkItems WHERE [System.TeamProject] = @project AND [System.WorkItemType] = 'Epic' AND ([System.State] = 'To Do' OR [System.State] = 'Doing') AND ([Microsoft.VSTS.Common.Priority] = 3 OR [Microsoft.VSTS.Common.Priority] = 4)"
  neededFields:
    - "assignedTo"
  evaluate:
    settings:
      closedStates:
        - "Closed"
        - "Done"
    checks:
      dataExists: true
      fields:
        assignedTo: #To check, whether the ticket is unassigned or not
          fieldName: "assignedTo"
          conditions:
            illegal:
              - ""
