# SPDX-FileCopyrightText: 2024 grow platform GmbH
#
# SPDX-License-Identifier: MIT

version: 2
updates:
  - package-ecosystem: 'github-actions' # Necessary to update action hashes
    directory: '/'
    schedule:
      interval: 'weekly'
    # Allow up to 3 opened pull requests for github-actions versions
    open-pull-requests-limit: 3
