name: Test onyx pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - "test-onyx-caching"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: ">=1.20.0"
          cache: true
      - name: Setup Golang caches
        id: go-cache
        uses: actions/cache@v3
        with:
          path: |
            onyx
          key: ${{ runner.os }}-onyx
          restore-keys: |
            ${{ runner.os }}-onyx
      - name: Show cache contents
        run: |
          ls -ltr onyx
          ls -ltr onyx/bin
      - if: ${{ steps.go-cache.outputs.cache-hit != 'true' }}
        name: Build
        working-directory: onyx
        run: |
          make setup
          make build