name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
      - "build-core-image"
  pull_request:
    branches:
      - "main"

permissions:
  contents: read
  packages: write
  id-token: write
  attestations: write

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-onyx:
    uses: ./.github/workflows/build-onyx.yml

  build-typescript-apps:
    uses: ./.github/workflows/build-typescript-apps.yml

  build-backend:
    uses: ./.github/workflows/build-backend.yml

  build-backend-docker-image:
    # if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    needs:
      - build-backend
    uses: ./.github/workflows/build-backend-docker-image.yml

  build-core-docker-image:
    # if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    needs:
      - build-onyx
      - build-typescript-apps
    uses: ./.github/workflows/build-core-docker-image.yml
