name: Build

on:
  push:
    branches: [ "main" ]
    paths:
      - 'onyx/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'onyx/**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        folder: [onyx]  # List your folders here

    steps:
      - uses: actions/checkout@v4
      - uses: bazel-contrib/setup-bazel@0.9.0
        with:
          # Avoid downloading Bazel every time.
          bazelisk-cache: true
          # Store build cache per workflow.
          disk-cache: ${{ github.workflow }}
          # Share repository cache between workflows.
          repository-cache: true

      - name: Build with Bazel
        working-directory: ${{ matrix.folder }}
        run: bazel build //...

      - name: Test with Bazel
        working-directory: ${{ matrix.folder }}
        run: bazel test //...