name: Build and Test

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  build-onyx:
    uses: ./.github/workflows/build-onyx.yml

  build-typescript-apps:
    uses: ./.github/workflows/build-typescript-apps.yml

  build-backend:
    uses: ./.github/workflows/build-backend.yml

  build-backend-docker-image:
    needs:
      - build-onyx
      - build-typescript-apps
      - build-backend
    uses: ./.github/workflows/build-backend-docker-image.yml
