# SPDX-FileCopyrightText: 2024 grow platform GmbH
#
# SPDX-License-Identifier: MIT

on:
  workflow_call:

jobs:
  build-ui-docker-image:
    runs-on: ubuntu-latest
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: b-s-f/yaku/yaku-ui
    steps:
      - uses: actions/checkout@v4

      - name: Log in to the Container Registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate image tag
        run: |
          base_tag="${{ env.IMAGE_NAME }}:$( date '+%Y-%m-%d_%H-%M-%S' )-$(echo ${GITHUB_SHA} | cut -c1-7)"
          image_tag="${{ env.REGISTRY }}/$base_tag"
          echo "IMAGE_TAG=$image_tag" >> $GITHUB_ENV

      - name: Build Docker Image
        uses: docker/build-push-action@v5
        with:
          pull: true
          push: true
          tags: ${{ env.IMAGE_TAG }}
          context: ./yaku-ui/qg-service-ui
          file: yaku-ui/qg-service-ui/Dockerfile
          platforms: linux/amd64
