on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
      - reopened
    paths:
      - user-documentation/**

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          persist-credentials: false
      - name: Install uv
        uses: astral-sh/setup-uv@v3
      - uses: actions/cache@v3
        id: cache-venv
        name: Cache virtual environment
        with:
          path: user-documentation/.venv/
          key: ${{ hashFiles('user-documentation/requirements.lock', 'user-documentation/Makefile') }}
      - name: Setup virtual environment
        if: ${{ steps.cache-venv.outputs.cache-hit != 'true' }}
        run: |
          make -C user-documentation prepare
      - name: Sphinx Build
        run: |
          make -C user-documentation openapi
          make -C user-documentation html
        env:
          SPHINXOPTS: '-W'
