on:
  workflow_call:

jobs:
  build-core-docker-image:
    runs-on: ubuntu-latest
    env:
      REGISTRY: ghcr.io
    steps:
      - uses: actions/checkout@v4

      - name: Restore Onyx Cache
        uses: actions/cache/restore@v4
        with:
          path: onyx/bin
          key: onyx-${{ hashFiles('onyx/**') }}

      - name: Restore TypeScript Apps Cache
        uses: actions/cache/restore@v4
        with:
          path: yaku-apps-typescript
          key: typescript-apps-${{ hashFiles('yaku-apps-typescript/**') }}

      - name: Restore Python Apps Cache
        uses: actions/cache/restore@v4
        with:
          path: yaku-apps-python/dist
          key: python-apps-${{ hashFiles('yaku-apps-python/**') }}

      - name: Log in to the Container Registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker Image
        uses: docker/build-push-action@v5
        with:
          pull: true
          push: true
          tags: ghcr.io/b-s-f/yaku/core:latest
          context: .
          target: development
          file: core-image/Dockerfile
          platforms: linux/amd64
