# SPDX-FileCopyrightText: 2024 grow platform GmbH
#
# SPDX-License-Identifier: MIT

on:
  workflow_call:

jobs:
  build-typescript-apps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check for cache hit
        id: cache
        uses: actions/cache/restore@v4
        with:
          path: yaku-apps-typescript
          key: typescript-apps-${{ hashFiles('yaku-apps-typescript/**') }}
          lookup-only: true

      - name: Setup Node.js
        if: steps.cache.outputs.cache-hit != 'true'
        uses: actions/setup-node@v4
        with:
          node-version: 22
          check-latest: true
          cache: 'npm'
          cache-dependency-path: yaku-apps-typescript/package-lock.json

      - name: Install and Build
        if: steps.cache.outputs.cache-hit != 'true'
        working-directory: yaku-apps-typescript
        run: |
          npm ci -ws --include-workspace-root
          npm run build
          npm ci -ws --include-workspace-root

      - name: Lint
        if: steps.cache.outputs.cache-hit != 'true'
        working-directory: yaku-apps-typescript
        run: |
          npm run lint --workspaces --if-present

      - name: Run Unit Tests
        if: steps.cache.outputs.cache-hit != 'true'
        working-directory: yaku-apps-typescript
        run: npm run test --workspaces --if-present

      - name: Save Cache
        if: steps.cache.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          path: yaku-apps-typescript
          key: ${{ steps.cache.outputs.cache-primary-key }}
