name: Build chart

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - 'chart/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'chart/**'

env:
  REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: bazel-contrib/setup-bazel@0.9.0
        with:
          # Avoid downloading Bazel every time.
          bazelisk-cache: true
          # Store build cache per workflow.
          disk-cache: ${{ github.workflow }}
          # Share repository cache between workflows.
          repository-cache: true

      - name: Build with Bazel
        working-directory: chart
        run: bazel build //...

      - name: Test with Bazel
        working-directory: chart
        run: bazel test //...

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push the chart to the OCI registry
        working-directory: chart
        run: bazel run //:yaku_helm.push_registry