name: Build TypeScript Apps

on:
  workflow_call:

jobs:
  build-typescript-apps:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - name: Cache Turbo Build Setup
        uses: actions/cache@v4
        with:
          path: yaku-apps-typescript/.turbo
          key: typescript-apps-turbo-${{ github.sha }}
          restore-keys: |
            typescript-apps-turbo-

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          check-latest: true
          cache: 'npm'
          cache-dependency-path: yaku-apps-typescript/package-lock.json

      - name: Restore Cache if Exists
        id: cache
        uses: actions/cache/restore@v4
        with:
          path: yaku-apps-typescript
          key: typescript-apps-${{ hashFiles('yaku-apps-typescript/**') }}

      - name: Install and Build
        if: steps.cache.outputs.cache-hit != 'true'
        working-directory: yaku-apps-typescript
        run: |
          npm ci -ws --include-workspace-root
          npm run build

      - name: Save Cache
        uses: actions/cache/save@v4
        with:
          path: yaku-apps-typescript
          key: ${{ steps.cache.outputs.cache-primary-key }}
