# SPDX-FileCopyrightText: 2024 grow platform GmbH
#
# SPDX-License-Identifier: MIT

on:
  workflow_call:

jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check for cache hit
        id: cache
        uses: actions/cache/restore@v4
        with:
          path: qg-api-service
          key: qg-api-service-${{ hashFiles('qg-api-service/**') }}
          lookup-only: true

      - name: Setup Node.js
        if: steps.cache.outputs.cache-hit != 'true'
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"
          cache-dependency-path: qg-api-service/package-lock.json

      - name: Install and Build
        if: steps.cache.outputs.cache-hit != 'true'
        working-directory: qg-api-service
        run: |
          npm ci -ws --include-workspace-root
          npm run build

      - name: Run all unit tests
        if: steps.cache.outputs.cache-hit != 'true'
        working-directory: qg-api-service
        run: |
          npm run test:cov --workspaces --if-present

      - name: Yaku Service Unit Tests
        if: steps.cache.outputs.cache-hit != 'true'
        working-directory: qg-api-service/qg-api-service
        run: npm run test:cov && npm run test:update-cobertura-file

      - name: Yaku Service Integration Tests
        if: steps.cache.outputs.cache-hit != 'true'
        working-directory: qg-api-service/qg-api-service
        run: npm run test:integration

      - name: Client Lib Unit Tests
        if: steps.cache.outputs.cache-hit != 'true'
        working-directory: qg-api-service/yaku-client-lib
        run: npm run test:cov

      - name: Yaku CLI Unit Tests
        if: steps.cache.outputs.cache-hit != 'true'
        working-directory: qg-api-service/yaku-cli
        run: npm run test:cov

      - name: Yaku CLI Integration Tests
        if: steps.cache.outputs.cache-hit != 'true'
        working-directory: qg-api-service/yaku-cli
        run: npm run test:integration

      - name: Save Cache
        if: steps.cache.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          path: qg-api-service
          key: ${{ steps.cache.outputs.cache-primary-key }}
