name: Build Backend Docker Image

on:
  workflow_call:

jobs:
  build-backend-docker-image:
    runs-on: ubuntu-latest
    env:
      REGISTRY: ghcr.io
    steps:
      - uses: actions/checkout@v4

      - name: Restore Onyx Cache
        uses: actions/cache/restore@v4
        with:
          path: onyx/bin
          key: onyx-${{ hashFiles('onyx/**') }}

      - name: Restore TypeScript Apps Cache
        uses: actions/cache/restore@v4
        with:
          path: yaku-apps-typescript
          key: typescript-apps-${{ hashFiles('yaku-apps-typescript/**') }}

      - name: Restore Backend Cache
        uses: actions/cache@v4
        with:
          path: qg-api-service
          key: qg-api-service-${{ hashFiles('qg-api-service/**') }}

      - name: Log in to the Container Registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker Image
        uses: docker/build-push-action@v5
        with:
          pull: true
          push: true
          build-args: |
            BASE_IMAGE_WORKFLOW_NAME=node:22-alpine
          tags: ghcr.io/b-s-f/yaku/api-image-test:test
          context: ./qg-api-service
          file: qg-api-service/qg-api-service/Dockerfile
          platforms: linux/amd64
