name: Test Onyx Pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - "test-onyx-caching"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 5
      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: ">=1.20.0"
          cache: true
      - name: restore cache if exists
        id: go-cache
        uses: actions/cache/restore@v4
        with:
          path: |
            onyx/bin
          key: onyx-${{ hashFiles('onyx/**') }}
          lookup-only: true
          restore-keys: |
            onyx-
      - if: ${{ steps.go-cache.outputs.cache-hit != 'true'}}
        name: Build
        working-directory: onyx
        run: |
          make setup
          make build
      - name: Save cache
        id: save-cache
        uses: actions/cache/save@v4
        with:
          path: |
            onyx/bin
          key: onyx-${{ hashFiles('onyx/**') }}
  test:
    runs-on: ubuntu-latest
    needs: 
      - build
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: restore cache if exists
        id: go-cache
        uses: actions/cache/restore@v4
        with:
          path: |
            onyx/bin
          key: onyx-${{ hashFiles('onyx/**') }}
          restore-keys: |
            onyx-
      - name: Check
        run: ls -ltr onyx/bin
      