name: Build Onyx

on:
  workflow_call:

jobs:
  build-onyx:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ">=1.20.0"
          cache: true
          cache-dependency-path: onyx/go.sum

      - name: Restore Cache if Exists
        id: onyx-cache
        uses: actions/cache/restore@v4
        with:
          path: onyx/bin
          key: onyx-${{ hashFiles('onyx/**') }}
          lookup-only: true

      - name: Build
        if: steps.onyx-cache.outputs.cache-hit != 'true'
        working-directory: onyx
        run: |
          make setup
          make build

      - name: Save Cache
        uses: actions/cache/save@v4
        with:
          path: onyx/bin
          key: ${{ steps.onyx-cache.outputs.cache-primary-key }}
