name: Publish Autopilot Utils to PyPI

on:
  workflow_dispatch:
    
env:
  PYTHON_APPS_FOLDER: yaku-apps-python

jobs:
  build-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: ${{ env.PYTHON_APPS_FOLDER }}
      
      - name: Put all files from ${{ env.PYTHON_APPS_FOLDER }} in cwd
        run: |
          mv ${{ env.PYTHON_APPS_FOLDER }}/* .
      
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      
      - name: Setup pants
        uses: pantsbuild/actions/init-pants@v8
        with:
          gha-cache-key: cache0
          named-caches-hash: ${{ hashFiles('/3rdparty/*.txt') }}
      
      - name: Build wheel
        run: |
          pants package ./packages/autopilot-utils/::
      
      - name: Store the distribution packages
        uses: actions/upload-artifact@v4
        with:
          name: autopilot-utils-package-distributions
          path: dist/*.whl


  publish-to-pypi:
    runs-on: ubuntu-latest
    needs: [build-package]
    env:
      name: pypi
      url: https://pypi.org/p/autopilot-utils
    permissions:
      id-token: write
    steps:
      - name: Download distribution packages
        uses: actions/download-artifact@v4
        with:
          name: autopilot-utils-package-distributions
          path: dist/

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          verify-metadata: false